elbow/apps/order/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.decorators.csrf import csrf_exempt

from .views import (OrderCreate,
                    OrderLoanAgreementView,
                    OrderPayment,
                    UserOrderList,
                    OrderDetail,
                    OrderWebhook)

urlpatterns = patterns('',
                       url(r'^$',
                           UserOrderList.as_view(),
                           name='user_list'),

                       url(r'^(?P<project_slug>[\w-]+)/order/$',
                           OrderCreate.as_view(),
                           name='create'),

                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>[\w-]+)/loan-agreement/$',
                           OrderLoanAgreementView.as_view(),
                           name='loan_agreement'),

                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>.*)/payment/$',
                           OrderPayment.as_view(),
                           name='payment'),

                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>[\w-]+)/$',
                           OrderDetail.as_view(),
                           name='detail'),

                       #
                       # Payment integration, All are webhooks
                       #
                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>[\w-]+)/payment/successful/$',
                           OrderDetail.as_view(template_name='order/order-payment_success.html'),
                           name='payment_success'),

                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>[\w-]+)/payment/failure/$',
                           OrderDetail.as_view(template_name='order/order-payment_failed.html'),
                           name='payment_failure'),

                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>[\w-]+)/payment/webhook/$',
                           csrf_exempt(OrderWebhook.as_view()),
                           name='payment_webhook'),)

elbow/urls.py
# -*- coding: UTF-8 -*-
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.decorators.cache import never_cache

from elbow.apps.public.views import LoginView, SignupView

admin.site.site_header = 'Todayhaus Administration'


urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^api/v1/', include('elbow.apps.api.urls', namespace='api')),

    # Projects
    url(r'^projects/', include('elbow.apps.project.urls', namespace='project')),
    # Orders
    url(r'^orders/', include('elbow.apps.order.urls', namespace='order')),
    # Documents
    url(r'^documents/', include('elbow.apps.document.urls', namespace='document')),
    # Paymill
    # url(r'^paymill/', include('dj_paymill.urls', namespace='paymill')),
    # User Auth
    # url(r'^auth/token/', 'rest_framework_jwt.views.obtain_jwt_token'),
    # url(r'^auth/token/refresh/', 'rest_framework_jwt.views.refresh_jwt_token'),
    # url(r'^auth/', include('rest_auth.urls')),
    # url(r'^auth/registration/', include('rest_auth.registration.urls')),
    url(r'^accounts/login/', never_cache(LoginView.as_view()), name='account_login'),
    url(r'^accounts/signup/', never_cache(SignupView.as_view()), name='account_signup'),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^', include('elbow.apps.public.urls', namespace='public')),
    url(r'^p/', include('pages.urls')), # check public/urls.py
    url(r'^robots\.txt', include('robots.urls')),
    url(r'^', include('django.contrib.auth.urls')),

) + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elbow/apps/order/models.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.template import loader
from django.core.urlresolvers import reverse
from django.utils.translation import activate
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType

from secupay import SecuPay
from jsonfield import JSONField
from pinax.eventlog.models import log
from djmoney.models.fields import MoneyField

from .apps import ORDER_STATUS, ORDER_PAYMENT_TYPE, SECUPAY_BANK_DATA
from .managers import OrderManager

from shortuuidfield import ShortUUIDField

import re
import time
import logging
logger = logging.getLogger('django.request')


class Order(models.Model):
    BASE_URL = getattr(settings, 'BASE_URL', 'http://localhost:8009')

    ORDER_STATUS = ORDER_STATUS
    ORDER_PAYMENT_TYPE = ORDER_PAYMENT_TYPE

    SECUPAY = SecuPay(settings=settings)
    SECUPAY_BANK_DATA = SECUPAY_BANK_DATA

    uuid = ShortUUIDField(db_index=True)
    user = models.ForeignKey('auth.User')
    project = models.ForeignKey('project.Project')
    payment_option = models.ForeignKey('order.PaymentOption', blank=True, null=True)

    transaction_id = models.CharField(max_length=128, blank=True, null=True)

    title = models.CharField(max_length=24, blank=True, null=True)
    customer_name = models.CharField(max_length=255, blank=True, null=True)
    company_name = models.CharField(max_length=255, blank=True, null=True)
    dob = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)

    address_1 = models.CharField(max_length=255, blank=True, null=True)
    address_2 = models.CharField(max_length=255, blank=True, null=True)
    postcode = models.CharField(max_length=24, blank=True, null=True)
    city = models.CharField(max_length=24, blank=True, null=True)
    country = models.CharField(max_length=64, blank=True, null=True)

    status = models.CharField(choices=ORDER_STATUS.get_choices(),
                              default=ORDER_STATUS.created,
                              max_length=64,
                              db_index=True)

    payment_type = models.CharField(choices=ORDER_PAYMENT_TYPE.get_choices(),
                                    default=ORDER_PAYMENT_TYPE.debit,
                                    max_length=24,
                                    db_index=True)

    amount = MoneyField(max_digits=10, decimal_places=2, default_currency='EUR')

    shipping = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    tracking_number = models.CharField(max_length=128, blank=True, null=True)

    data = JSONField(default={})

    expiration = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    documents = models.ManyToManyField('document.Document')

    objects = OrderManager()

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')
        ordering = ('-created_at',)

    @property
    def display_payment_type(self):
        return self.ORDER_PAYMENT_TYPE.get_desc_by_value(self.payment_type)

    @property
    def url(self):
        """
        Basic State-Machine need to integrate
        """
        url_kwargs = {'project_slug': self.project.slug, 'uuid': self.uuid}

        if self.status in [self.ORDER_STATUS.paid, self.ORDER_STATUS.processing]:
            return reverse('order:detail', kwargs=url_kwargs)

        if self.status == self.ORDER_STATUS.created:
            #
            # Has completed primary step but may need to agree to
            # large sum agreement, either way they must ahve the opportunity
            # to download the load agreement or not
            #
            return reverse('order:loan_agreement', kwargs=url_kwargs)

        if self.status == self.ORDER_STATUS.loan_agreement:
            #
            # Completed the steps but needs to pay
            #
            return reverse('order:payment', kwargs=url_kwargs)
        #
        # Default out to show order detail page
        #
        return reverse('order:detail', kwargs=url_kwargs)

    @property
    def is_large_amount(self):
        """
        In order to be sent to secupay, we must be in "processing" status AND have a None for transaction_id
        """
        return self.amount.amount >= 1000

    @property
    def can_send_payment(self):
        """
        In order to be sent to secupay, we must be in "processing" status AND have a None for transaction_id
        """
        return self.status in [self.ORDER_STATUS.processing] and self.transaction_id in [None, '']

    @property
    def can_continue_process(self):
        """
        If the user has not completed their investment process allow them to continue via this check
        """
        return self.status in [self.ORDER_STATUS.created,
                               self.ORDER_STATUS.loan_agreement] and self.transaction_id in [None, '']

    @property
    def content_type(self):
        return ContentType.objects.filter(app_label='order', model='order').first()

    @property
    def log_history(self):
        return self.content_type.log_set.filter(object_id=self.pk)

    @property
    def url_success(self):
        activate(settings.LANGUAGE_CODE)
        return '%s%s' % (self.BASE_URL, reverse('order:payment_success', kwargs={'project_slug': self.project.slug, 'uuid': self.uuid}))

    @property
    def cancel_order_url(self):
        """
        URL is used for the "back to basket" functionlity at secupay
        NEVER sent via webhooks or 301 so this is effectively back_to_shop or cancel_order_url
        """
        activate(settings.LANGUAGE_CODE)
        return '%s%s' % (self.BASE_URL, reverse('order:create', kwargs={'project_slug': self.project.slug}))

    @property
    def url_webhook(self):
        activate(settings.LANGUAGE_CODE)
        return '%s%s' % (self.BASE_URL, reverse('order:payment_webhook', kwargs={'project_slug': self.project.slug, 'uuid': self.uuid}))

    @property
    def address(self):
        return loader.render_to_string('order/_address.html', {
                'address_1': self.address_1,
                'address_2': self.address_2,
                'postcode': self.postcode,
                'city': self.city,
                'country': self.country,
        })

    def __unicode__(self):
        return '%s - %s (%s)' % (self.amount, self.transaction_id, self.payment_type)

    def make_payment(self, user):
        """
        Primary make payment interface returns the iframe url
        """
        resp = {}

        amount = str(self.amount.amount)
        logger.info('make_payment: {order} {amount} {type}'.format(order=self,
                                                                   amount=amount,
                                                                   type=self.payment_type))

        secupay_required_values = {
            "purpose": 'TodayCapital-%d' % self.pk,  # Shown to user on bank statement
            "firstname": self.customer_name.split(' ')[0],
            "lastname": ' '.join(self.customer_name.split(' ')[1:]),
            "street": self.address_1,
            "housenumber": self.address_2,
            "zip": self.postcode,
            "city": self.city,
            "country": self.country,
            "email": self.user.email,
        }

        resp = self.SECUPAY.payment().make_payment(amount=amount,
                                                   payment_type=self.payment_type,
                                                   url_success=self.url_success,
                                                   url_failure=self.cancel_order_url,
                                                   url_push=self.url_webhook,
                                                   **secupay_required_values)

        log(
            user=user,
            action="order.lifecycle.payment.make_payment",
            obj=self,
            extra=resp
        )

        self.data = resp.get('data', {})

        self.transaction_id = self.data.get('hash')

        self.tracking_number = self.data.get('purpose')

        #
        # @NOTE Secupay limitation
        # Will happen in the case of direct debit, no purpose will be provided.
        # thus we need to use their hash as a relatively simple code as requested by TC
        #
        if self.tracking_number is None:
            #
            # Get the Actual status
            #
            time.sleep(2)  # is required when the email was sent right after make_payment was called.
            #
            status_resp = self.SECUPAY.payment().status(hash=self.transaction_id)
            status_resp = status_resp.get('data', {})
            self.tracking_number = 'TA %s' % status_resp.get('trans_id')

            self.data['status_resp'] = status_resp

            log(
                user=user,
                action="order.lifecycle.payment.missing_trans_id",
                obj=self,
                extra=status_resp
            )

            if not self.tracking_number:
                #
                # LAST FALBACK OPPORTUNITY
                # where hash is upptaaluefxm967881
                # (Pdb) match.groups()
                # (u'upptaaluefxm', u'967881')
                #
                match = re.search('^([a-zA-Z]+)(\d+)$', self.transaction_id)
                self.tracking_number = 'TA %s' % match.group(2)

                log(
                    user=user,
                    action="order.lifecycle.payment.fallback_missing_trans_id",
                    obj=self,
                    extra=status_resp
                )

        # Replace the TA- with TH- as requestd by client
        # we save the original TA-***** number in the order.data json
        self.tracking_number = self.tracking_number.replace('TA ', 'TC-')

elbow/apps/order/templates/order/admin/order-logs.html
{% extends "admin/base.html" %}{% load i18n admin_urls admin_static admin_modify humanize %}

{% block content %}
    <!-- CUSTOM ORDERS -->
   <h1>{% trans 'Order Logs' %}</h1>
   <div class="well">
     <p><b>Amount:</b> {{ order.amount }}</p>
     <p><b>User:</b> {{ order.user }}</p>
     <p><b>Customer:</b> {{ order.customer_name }}</p>
     <p><b>Secupay ID:</b> {{ order.transaction_id }}</p>
     <p><b>Secupay Purpose:</b> {{ order.tracking_number }}</p>
     <p><b>Status:</b> {{ order.status }}</p>
   </div>
   <table>
    <thead>
    <tr>
        <th class="required">Date</th>
        <th class="required">Event</th>
        <th class="required">Data</th>
    </tr>
    </thead>

     <tbody>
     {% for log in object_list %}
        <tr class="form-row {% cycle "row1" "row2" %}">
            <td class="field-uuid">
                {{ log.timestamp|naturaltime }}
                <br/><small>{{ log.timestamp }}</small>
            </td>
            <td class="field-action">
              {{ log.action }}
            </td>
            <td class="field-extra">
              {{ log.extra }}
            </td>
        </tr>
     {% empty %}
         <tr class="form-row {% cycle "row1" "row2" %}">
             <td colspan="10"><b>{% trans 'No logs found' %}</b></td>
         </tr>
     {% endfor %}
     </tbody>
   </table>
   <!-- END CUSTOM ORDERS -->
    {{ block.super }}
{% endblock %}

{% block extrahead %}
    {{ block.super }}
    <script type="text/javascript">
    'use strict';
    (function($) {

    })(django.jQuery);
    </script>
{% endblock %}

elbow/apps/order/templates/order/admin/order_change_form.html
{% extends "admin/change_form.html" %}
{% load i18n admin_urls admin_static admin_modify humanize %}


{% block after_related_objects %}
    <!-- PROJECT LOG -->
    <h1>{% trans 'Project News' %}</h1>
    {% if original.pk %}<a href="{% url 'admin:add_project_news' pk=original.pk %}" target="_NEW">{% trans 'Add News' %}</a><br/>{% endif %}
   <table>
    <thead>
    <tr>
        <th class="required">Date</th>
        <th class="required">Note</th>
        <th>Actions</th>
    </tr>
    </thead>

     <!--<tbody>
     {% for news in original.news_history %}
        <tr class="form-row {% cycle "row1" "row2" %}">
            <td class="field-timestamp">
                <b>{% trans 'Date:' %}</b> <a title="{{ news.timestamp }}">{{ news.timestamp|naturaltime }}</a><br/>
            </td>
            <td class="field-note">
                <b>{% trans 'Note:' %}</b> {{ news.extra.note }}<br/>
            </td>
            <td class="action buttons">
              <a href="javascript:;" class="order-lifecycle-event" data-url="{% url 'admin:project_delete_news' project_pk=original.pk pk=news.pk %}">{% trans 'Delete' %}</a><br/>
            </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="3" class="action buttons">
          No Records Found
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>-->

    <!-- CUSTOM ORDERS -->
   <h1>{% trans 'Project Orders' %}</h1>
   <table>
    <thead>
    <tr>
        <th class="required">ID</th>
        <th class="required">Amount</th>
        <th class="required">Company</th>
        <th class="required">Customer</th>
        <th class="required">Address</th>
        <th class="required">Tracking Number</th>
        <th class="required">Payment type</th>
        <th class="required">Status</th>
        <th>Actions</th>
    </tr>
    </thead>

     <tbody>
     {% for order in original.order_set.all %}
        <tr class="form-row {% cycle "row1" "row2" %}">
            <td class="field-uuid">
                <a href=""><b>{{ order.uuid }}</b></a><br/>
                <b>{% trans 'Created:' %}</b> <a title="{{ order.created_at }}">{{ order.created_at|naturaltime }}</a><br/>
                <b>{% trans 'Updated:' %}</b> <a title="{{ order.created_at }}">{{ order.updated_at|naturaltime }}</a><br/>
            </td>
            <td class="field-amount">
                {{ order.amount }}
            </td>
            <td class="field-customer_name">
                {{ order.company_name }}
            </td>
            <td class="field-customer_name">
                {{ order.customer_name }}
            </td>
            <td class="field-address">
                {{ order.address }}
            </td>
            <td class="field-tracking_number">
                {{ order.tracking_number|default:"" }}
            </td>
            <td class="field-payment_type">
                {{ order.display_payment_type }}
            </td>
            <td class="field-status">
                {{ order.status }}
            </td>
            <td class="action buttons">
              {% if order.status == 'pending' and order.status != 'failed' %}
                {% if order.payment_type == 'prepay' %}<a href="javascript:;" class="order-lifecycle-event" data-url="{% url 'admin:order_marked_as_paid' uuid=order.uuid %}">{% trans 'Mark as Paid' %}</a><br/>{% endif %}
              {% endif %}
              <br/><a href="{% url 'admin:order_logs' uuid=order.uuid %}" target="_NEW" class="view-order-logs" data-url="{% url 'admin:order_logs' uuid=order.uuid %}">{% trans 'View Logs' %}</a><br/>
              {% comment %}{% if order.status != 'cancelled' and order.status != 'paid' %}
              <br/><a href="javascript:;" class="order-lifecycle-event" data-url="{% url 'admin:order_cancel' uuid=order.uuid %}">{% trans 'Cancel Order' %}</a><br/>
              {% endif %}{% endcomment %}
              {% if order.status == 'cancelled' or order.status == 'processing' %}
              <br/><a href="javascript:;" class="order-lifecycle-event" data-url="{% url 'admin:order_reset' uuid=order.uuid %}">{% trans 'Reset Order' %}</a><br/>
              {% endif %}
            </td>
        </tr>
     {% empty %}
         <tr class="form-row {% cycle "row1" "row2" %}">
             <td colspan="10"><b>{% trans 'No orders found' %}</b></td>
         </tr>
     {% endfor %}
     </tbody>
   </table>
   <!-- END CUSTOM ORDERS -->
    {{ block.super }}
{% endblock %}

{% block admin_change_form_document_ready %}
    {{ block.super }}
    <script type="text/javascript">
    'use strict';
    (function($) {

      $('.order-lifecycle-event').on('click', function (event) {
        event.preventDefault();
        var button = $(this);
        var url = button.data().url;
        console.log(url);
        $.ajax({
            url: url,
            type: 'POST',
            data: JSON.stringify({
            }),
            dataType: 'json',
            contentType: "application/json",
            beforeSend: function (request) {
                request.setRequestHeader("X-CSRFToken", '{{csrf_token}}');
                // disable the button
                button.prop('disabled', true);
            },
            error: function ( data ) {
                var payload = data.responseJSON;
                // enable the button again
                button.prop('disabled', false);
            },
            success: function ( data ) {
                //console.log(data)
                if ( data.status == 200 ) {
                }
                button.prop('disabled', false);
                document.location.reload();
            }
        });

      });
    })(django.jQuery);
    </script>
{% endblock %}