elbow/apps/project/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView, ListView

from .models import Project
from .views import ProjectDetailView, PDFPermalinkView


urlpatterns = patterns('',
                       url(r'^project-api/$', TemplateView.as_view(template_name='project/api-project-list.html')),
                       url(r'^$',
                           ListView.as_view(template_name='project/project-list.html',
                                            model=Project,
                                            queryset=Project.objects.public()),
                           name='list'),

                       url(r'^(?P<slug>[\w-]+)/media/(?P<media_slug>[\w-]+)/permalink/$',
                           PDFPermalinkView.as_view(),
                           name='media_permalink'),

                       url(r'^(?P<slug>[\w-]+)/$',
                           ProjectDetailView.as_view(),
                           name='detail'),)

elbow/urls.py
# -*- coding: UTF-8 -*-
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.decorators.cache import never_cache

from elbow.apps.public.views import LoginView, SignupView

admin.site.site_header = 'Todayhaus Administration'


urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^api/v1/', include('elbow.apps.api.urls', namespace='api')),

    # Projects
    url(r'^projects/', include('elbow.apps.project.urls', namespace='project')),
    # Orders
    url(r'^orders/', include('elbow.apps.order.urls', namespace='order')),
    # Documents
    url(r'^documents/', include('elbow.apps.document.urls', namespace='document')),
    # Paymill
    # url(r'^paymill/', include('dj_paymill.urls', namespace='paymill')),
    # User Auth
    # url(r'^auth/token/', 'rest_framework_jwt.views.obtain_jwt_token'),
    # url(r'^auth/token/refresh/', 'rest_framework_jwt.views.refresh_jwt_token'),
    # url(r'^auth/', include('rest_auth.urls')),
    # url(r'^auth/registration/', include('rest_auth.registration.urls')),
    url(r'^accounts/login/', never_cache(LoginView.as_view()), name='account_login'),
    url(r'^accounts/signup/', never_cache(SignupView.as_view()), name='account_signup'),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^', include('elbow.apps.public.urls', namespace='public')),
    url(r'^p/', include('pages.urls')), # check public/urls.py
    url(r'^robots\.txt', include('robots.urls')),
    url(r'^', include('django.contrib.auth.urls')),

) + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elbow/apps/project/models.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from moneyed import Money

from django.db import models
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from django.contrib.contenttypes.models import ContentType

from djmoney.models.fields import MoneyField
from geoposition.fields import GeopositionField

from autoslug import AutoSlugField
from embed_video.fields import EmbedVideoField

from elbow.utils import CustomManagedStorage

from .apps import PROJECT_STATUS, USE_PAYMENTOPTIONS, INTEREST_TYPE
from .managers import ProjectManager

import os
import datetime


def _image_upload_path(instance, filename):
    filename, file_extension = os.path.splitext(filename)
    return 'project/%s/img-%s%s' % (slugify(instance.slug), slugify(filename), file_extension)


def _doc_upload_path(instance, filename):
    filename, file_extension = os.path.splitext(filename)
    return 'project/%s/doc-%s%s' % (slugify(instance.slug), slugify(filename), file_extension)


class Project(models.Model):
    """
    Base Project that can be invested in
    """
    PROJECT_STATUS = PROJECT_STATUS
    USE_PAYMENTOPTIONS = USE_PAYMENTOPTIONS
    INTEREST_TYPE = INTEREST_TYPE

    slug = AutoSlugField(populate_from='name')
    name = models.CharField(max_length=255)

    amount = MoneyField(max_digits=10, decimal_places=2, default_currency='EUR')
    minimum_investment = MoneyField(max_digits=10, decimal_places=2, default=500, default_currency='EUR')
    maximum_investment = MoneyField(max_digits=10, decimal_places=2, default=None, default_currency='EUR', blank=True, null=True)

    interest_type = models.CharField(choices=INTEREST_TYPE.get_choices(),
                                     default=INTEREST_TYPE.a,
                                     max_length=64,
                                     db_index=True)

    interest_rate = models.DecimalField(default=6.0, max_digits=6, decimal_places=2)
    interest_term = models.CharField(max_length=24, help_text=_('Format: 12m, 36m, 3y, 7y'), blank=True, null=True)

    proposition = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)

    building_type = models.CharField(max_length=255, blank=True, null=True)
    building_status = models.CharField(max_length=255, blank=True, null=True)
    building_location = models.CharField(max_length=255, blank=True, null=True)

    lat_long = GeopositionField(default='51.1655111, 6.2737308')

    documents = models.ManyToManyField('document.Document')

    term_sheet_doc = models.FileField(verbose_name=_('Term Sheet'),
                                      upload_to=_doc_upload_path,
                                      null=True,
                                      blank=True,
                                      storage=CustomManagedStorage())

    loan_agreement_doc = models.FileField(verbose_name=_('Loan Agreement'),
                                          upload_to=_doc_upload_path,
                                          max_length=255,
                                          null=True,
                                          blank=True,
                                          storage=CustomManagedStorage())

    # Sent to payment processor as description
    payment_description = models.CharField(max_length=255, blank=True, null=True)
    use_payment_options = models.CharField(choices=USE_PAYMENTOPTIONS.get_choices(),
                                           default=USE_PAYMENTOPTIONS.no,
                                           max_length=3,
                                           db_index=True)

    image = models.ImageField(upload_to=_image_upload_path,
                              storage=CustomManagedStorage(),
                              blank=True, null=True)
    video = EmbedVideoField(blank=True, null=True)

    status = models.CharField(choices=PROJECT_STATUS.get_choices(),
                              default=PROJECT_STATUS.pending,
                              max_length=64,
                              db_index=True)

    redirect_url = models.URLField(verbose_name=_('Redirect URL'),
                                   help_text=_('If present the detail page will redirect here'),
                                   blank=True,
                                   null=True)

    date_available = models.DateField(blank=True, null=True)
    expiration = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = ProjectManager()

    class Meta:
        verbose_name = _('Project')
        verbose_name_plural = _('Projects')
        ordering = ['-created_at']

    def __unicode__(self):
        return self.name

    @property
    def url(self):
        return reverse('project:detail', kwargs={'slug': self.slug})

    @property
    def invest_now_url(self):
        return reverse('order:create', kwargs={'project_slug': self.slug})

    @property
    def running_time(self):
        return '?'

    @property
    def is_available_for_investment(self):
        return datetime.datetime.combine(self.date_available, datetime.time(0, 0)) <= datetime.datetime.today() if self.date_available else True

    @property
    def num_backers(self):
        if getattr(settings, 'ELBOW_SHOW_POTENTIAL_PAYMENTS', False) is True:
            return self.order_set.potential().count()
        else:
            return self.order_set.paid().count()

    @property
    def percent(self):
        if self.amount.amount > 0:
            return round((float(self.revenue.amount) / float(self.amount.amount)) * 100, 2)
        else:
            return 0

    @property
    def revenue(self):
        if getattr(settings, 'ELBOW_SHOW_POTENTIAL_PAYMENTS', False) is True:
            qs = self.order_set.potential()
        else:
            qs = self.order_set.paid()

        amount = qs.annotate(sum=models.Sum('amount')).aggregate(models.Sum('sum')).get('sum__sum')
        return Money(amount, 'EUR') if amount else Money(0, 'EUR')

    @property
    def content_type(self):
        return ContentType.objects.filter(app_label='project', model='project').first()

    @property
    def news_history(self):
        return self.content_type.log_set.filter(object_id=self.pk)

    @property
    def term_sheet_doc_permalink(self):
        return reverse('project:media_permalink', kwargs={'slug': self.slug, 'media_slug': 'term-sheet'}) if self.term_sheet_doc else None

    @property
    def loan_agreement_doc_permalink(self):
        return reverse('project:media_permalink', kwargs={'slug': self.slug, 'media_slug': 'loan-agreement'}) if self.loan_agreement_doc else None

elbow/apps/project/api/views.py
# -*- coding: UTF-8 -*-
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.viewsets import ReadOnlyModelViewSet
from rest_framework.authentication import SessionAuthentication

from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _

from ..models import Project
from .serializers import (ProjectSerializer,)

from urlparse import urljoin


class ProjectListAPIViewset(ReadOnlyModelViewSet):
    model = Project
    serializer_class = ProjectSerializer
    queryset = Project.objects.public()
    lookup_field = 'slug'


class ListMenuItems(APIView):
    """
    View to list menu items depending on if user is logged in or not
    """
    authentication_classes = (SessionAuthentication,)

    def get(self, request, format=None):
        """
        Return a list of all users.
        """
        menu_items = []

        if request.user.is_authenticated():
            menu_items = [
                {
                    'name': _('Change Password'),
                    'url': urljoin(settings.BASE_URL, reverse('account_change_password')),
                },
                {
                    'name': _('Logout'),
                    'url': urljoin(settings.BASE_URL, reverse('account_logout')),
                },
            ]
        else:
            menu_items = [
                {
                    'name': _('Login'),
                    'url': urljoin(settings.BASE_URL, reverse('account_login')),
                },
                {
                    'name': _('Register'),
                    'url': urljoin(settings.BASE_URL, reverse('account_signup')),
                }
            ]

        return Response(menu_items)

elbow/apps/project/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponseRedirect
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, RedirectView
from django.core.urlresolvers import reverse

from elbow.apps.project.models import Project


class ProjectDetailView(DetailView):
    model = Project
    template_name = 'project/project-detail.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        #
        # if is removed or pending project
        #
        if self.object.status in [self.object.PROJECT_STATUS.pending, self.object.PROJECT_STATUS.removed]:
            raise Http404("Project is not available: {0}".format(self.object.PROJECT_STATUS.get_desc_by_value(self.object.status)))

        #
        # If a redirect url is set then redirect
        #
        if self.object.redirect_url:
            return HttpResponseRedirect(self.object.redirect_url)

        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class PDFPermalinkView(RedirectView):

    def get_object(self):
        return Project.objects.get(slug=self.kwargs.get('slug'))

    def get_redirect_url(self, *args, **kwargs):
        media_slug = self.kwargs.get('media_slug')
        project = self.get_object()
        document = None

        if media_slug in ['term-sheet', 'loan-agreement']:
            login_required = True
        else:
            #
            # Get the document object
            #
            document = get_object_or_404(project.documents, uuid=media_slug)
            login_required = document.login_required

        # Get the url
        if document is None:
            # we have a hardcoded file
            if media_slug == 'term-sheet':
                url = project.term_sheet_doc.url
            elif media_slug == 'loan-agreement':
                url = project.loan_agreement_doc.url
        else:
            # is a standard document so get its url
            url = document.document.url

        if login_required is True:
            # if authenticated
            if self.request.user.is_authenticated() is True:
                return url
            else:
                # not autenticated
                return reverse('account_login')

        return url

elbow/apps/project/templates/project/_docs.html
{% load i18n static %}
<div class="table-responsive">
  <table class="table table-responsive table-striped">
  {% if header %}
  <tr>
    <th colspan="2" class="bg-primary"><b>{% trans 'Documents' %}</b></th>
  </tr>
  {% endif %}
  {% if expose_document.uuid %}
  <tr>
    <td>{% trans 'Exposé TodayHaus' %}</td>
    <td><a href="{% url 'project:media_permalink' slug=project_slug media_slug=expose_document.uuid %}" target="_NEW" class="btn btn-link btn-primary">{% trans '.PDF Download' %}</a></td>
  </tr>
  {% endif %}
  {% if loan_agreement %}
  <tr>
    <td>{% trans 'Generic Loan Agreement' %}</td>
    <td><a href="{{ loan_agreement }}" target="_NEW" class="btn btn-link btn-primary">{% trans '.PDF Download' %}</a></td>
  </tr>
  {% endif %}
  {% if term_sheet %}
  <tr>
    <td>{% trans 'Term Sheet' %}</td>
    <td><a href="{{ term_sheet }}" target="_NEW" class="btn btn-link btn-primary">{% trans '.PDF Download' %}</a></td>
  </tr>
  {% endif %}
  {% if finance_plan.uuid %}
  <tr>
    <td>{% trans 'Finanzplan' %}</td>
    <td><a href="{% url 'project:media_permalink' slug=project_slug media_slug=finance_plan.uuid %}" target="_NEW" class="btn btn-link btn-primary">{% trans '.PDF Download' %}</a></td>
  </tr>
  {% endif %}

  {% for row in documents %}
    <tr>
      <td>{{ row.name }}</td>
      
      <td><a href="{% url 'project:media_permalink' slug=project_slug media_slug=row.uuid %}" target="_NEW" class="btn btn-link btn-primary">{% trans '.PDF Download' %}</a></td>
    </tr>
  {% endfor %}

  </table>
</div>

elbow/apps/project/templates/project/_preview.html
{% load i18n project_tags %}

{% for project in project_list %}
  <div class="row featurette">
    <div class="col-md-7 col-md-push-3">
      <h3 class="featurette-heading"><a href="{{ project.url }}">{{ project.name }}</a><br/><small><span class="text-muted">{{ project.proposition }}</span></small></h3>
      <p class="lead">{{ project.description }}</p>
      <p><a href="{{ project.url }}">{% trans "Details" %}</a></p>
    </div>
    <div class="col-md-3 col-md-pull-7">
      {% project_stats project %}
    </div>
  </div>
  <hr class="featurette-divider">
{% empty %}
{% endfor %}

elbow/apps/project/templates/project/_stats.html
{% load i18n l10n static djmoney %}
{% comment %}
This is view is deliberately without a outer div, allows you to define the project _stats width col-sm-2 or col-sm-7
{% endcomment %}

<a href="{{ project.url }}"><img src="{% get_media_prefix %}{{ project.image }}" class="img img-responsive center-block" alt="" title="" /></a>

<div class="">

  <div class="col-md-12 text-center">
    <p><b>{% trans "Investment Goal:" %}</b> {% money_localize project.amount %}</p>
  </div>

  <div class="col-md-12">
    {% if project.percent > 0 %}
    <div class="row progress">
      <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="{{ project.percent|unlocalize }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ project.percent|unlocalize }}%">
        <b>{{ project.percent }}%</b>
      </div>
    </div>
    {% else %}
      <div class="alert alert-success" role="alert">{% trans "<b>NB</b> Be one of the first to invest in this opportunity" %}</div>
    {% endif %}
  </div>

  {% if project.percent > 0 %}
  <div class="col-md-12">
    <div class="col-sm-6 text-center" style="min-height:80px;">
      <span class="badge">{{ project.num_backers }}</span>
      <br/><i class="glyphicon glyphicon-king" title="{% trans "Backers" %}"></i> {% trans "Backers" %}
    </div>
    <div class="col-sm-6 text-center" style="min-height:80px;">
      <span class="badge">{% money_localize project.revenue %}</span>
      <br/><i class="glyphicon glyphicon-euro" title="{% trans "Revenue" %}"></i> {% trans "Revenue" %}
    </div>
  </div>
  {% endif %}

</div><!-- End investment row -->

elbow/apps/project/templates/project/api-project-list.html
{% extends 'project/base.html' %}{% load i18n static project_tags %}

{% block page_title %}List of Projects{% endblock %}
{% block page_description %}A list of available projects{% endblock %}
{% block page_keywords %}list,projects{% endblock %}

{% block page_header %}
<div class="page-header clearfix">
    <div class="col-md-6" style="padding:0px;">
      <h1>Current Projects (from api)</h1>
    </div>
</div>
<div class="clearfix"></div>
{% endblock %}

{% block content %}
<div id="projects_list"></div>
{% endblock %}


{% block javascript %}

<script id="project-detail" type="text/x-handlebars-template">
{% verbatim %}
<div class="row featurette">
<div class="col-md-7 col-md-push-3">
  <h3 class="featurette-heading"><a href="{{ urls.invest_now }}">{{ name }}</a><br><small><span class="text-muted">{{ proposition }}</span></small></h3>
  <p class="lead">{{ description }}</p>
  <p><a href="{{ urls.invest_now }}">Invest Now</a></p>
</div>
<div class="col-md-3 col-md-pull-7">

  <a href="{{ urls.invest_now }}"><img src="{{ image }}" class="img img-responsive center-block" alt="" title=""></a>
  <div class="">
    <div class="col-md-12 text-center">
      <p><b>Investment Goal:</b> {{ amount.amount }} €</p>
    </div>
    <div class="col-md-12">

      <div class="row progress">
        <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="{{ percent }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ percent }}%">
          <b>{{ percent }}%</b>
        </div>
      </div>

    </div>

    <div class="col-md-12">
      <div class="col-sm-6 well well-sm text-center">
        <span class="badge">{{ num_backers }}</span>
        <br><i class="glyphicon glyphicon-king" title="Backers"></i> Backers
      </div>
      <div class="col-sm-6 well well-sm text-center">
        <span class="badge">{{ revenue.amount }} €</span>
        <br><i class="glyphicon glyphicon-euro" title="Revenue"></i> Revenue
      </div>
    </div>

    </div><!-- End investment row -->
  </div>

</div>
{% endverbatim %}
</script>

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.min.js"></script>
<script type="text/javascript" src="{% static 'js/jquery.plugin.elbow.projects.js' %}"></script>
<script type="text/javascript" id="elbow-list_products" type="text/javascript">
$(document).ready(function () {
    $( "#projects_list" ).list_projects({
      source: $('#project-detail').html(),
      endpoint: '{{ BASE_URL }}/api/v1/projects/'
    });
});
</script>
{% endblock %}

elbow/apps/project/templates/project/project-detail.html
{% extends 'project/base.html' %}{% load pipeline i18n l10n static djmoney embed_video_tags leaflet_tags project_tags %}

{% block page_title %}{{ project.name }} - Project Detail{% endblock %}
{% block page_description %}A list of available projects{% endblock %}
{% block page_keywords %}list,projects{% endblock %}

{% block page_header %}
<div class="page-header clearfix">
    <div class="col-md-9" style="padding:0px;">
      <h1>{{ project.name }}<br/><small>{{ project.proposition }}</small></h1>
    </div>
    <div class="col-md-3 text-center" style="padding-top:35px;">
      {% if object.is_available_for_investment %}
        <a href="{% url 'order:create' project_slug=project.slug %}" class="btn btn-primary btn-lg" name="" id="">{% trans "Invest Now" %}</a>
      {% else %}
        <a href="" class="btn btn-default btn-lg not-yet-available" name="" id="">{% blocktrans with available_from=object.date_available %}Available from {{ available_from }}{% endblocktrans %}</a>
      {% endif %}
    </div>
</div>
<div class="clearfix"></div>
{% endblock %}


{% block content %}
<div class="row">
  <div class="col-sm-5">
    {% project_stats project %}
  </div>
  <div class="col-sm-7">

      <div class="col-sm-5 well well-sm text-center">Interest rate: {{ project.interest_rate }} %</div>
      <div class="col-sm-5 col-sm-push-2 well well-sm text-center">Running Time: {{ project.running_time }}</div>
      <div class="clearfix"></div>
      <div class="col-sm-12">
        <h3>{% trans 'Overview' %}</h3>
        <p class="">{{ project.description }}</p>
        <p class="">minimum_investment: {{ project.minimum_investment }}</p>
        <p class="">target amount: {% money_localize project.amount %}</p>
        <p class="">interest_term: {{ project.interest_length }}</p>
        <p class="">Type of Interest rate: {{ project.interest_type }}</p>
        <p class="">Funding ends: {{ project.expiration }}</p>
      </div>

  </div>

</div><!-- End row -->

<!--   <div class="col-md-12">
{% if project.percent > 0 %}
<div class="row progress">
  <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="{{ project.percent }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ project.percent }}%">
    {{ project.percent }}%
  </div>
</div>
{% else %}
  <div class="alert alert-success" role="alert">{% trans "<b>NB</b> Be one of the first to invest in this opportunity" %}</div>
{% endif %}
</div> -->
<hr/>
<ul id="project-tabs" class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active"><a href="#project-documents" aria-controls="messages" role="tab" data-toggle="tab">{% trans 'Documents' %}</a></li>
  {# <li role="presentation"><a href="#project-description" aria-controls="home" role="tab" data-toggle="tab">{% trans 'Project description' %}</a></li> #}
  {# <li role="presentation"><a href="#project-participation" aria-controls="profile" role="tab" data-toggle="tab">{% trans 'Participation Model' %}</a></li> #}
  <li role="presentation"><a href="#project-news" aria-controls="messages" role="tab" data-toggle="tab">{% trans 'Latest News' %}</a></li>
  {# <li role="presentation"><a href="#project-faq" aria-controls="messages" role="tab" data-toggle="tab">{% trans 'F.A.Q' %}</a></li> #}
</ul>

<div class="tab-content">

  <div id="project-documents" role="tabpanel" class="tab-pane fade in active">
    <h3>{% trans 'Documents' %}</h3>
    {% project_docs project header=False %}
  </div>

  <div id="project-description" role="tabpanel" class="tab-pane fade">
    <div class="row">
      <div class="col-sm-6">
        <h3>{% trans 'Building Details' %}</h3>
        <p class="">building_type: {{ project.building_type }}</p>
        <p class="">building_status: {{ project.building_status }}</p>
        <p class="">building_location: {{ project.building_location }}</p>
      </div>
      <div class="col-sm-6">
        <h3>{% trans 'Map' %}</h3>
        {% leaflet_map 'location_map' callback="window.map_init_basic" %}
      </div>
    </div>
  </div>

  <div id="project-participation" role="tabpanel" class="tab-pane fade">
    <h3>{% trans 'How it works' %}</h3>
    <div class="col-sm-12">
      <img src="{% get_static_prefix %}img/sharing-model.png" class="img img-responsive" title="" alt="" />
    </div>
  </div>

  <div id="project-news" role="tabpanel" class="tab-pane fade">
    <div class="col-sm-12"><!-- Loaded via js --></div>
  </div>

  <div id="project-faq" role="tabpanel" class="tab-pane fade">
    <div class="col-sm-12">
      <h3>{% trans 'F.A.Q' %}</h3>
      <p>Please provide FAQ content</p>

      <div class="list-group">
        <a href="javascript:;" target="_NEW" class="list-group-item faq">
          <p><b>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</b></p>
          <div class="answer collapse">Ut sodales maximus mi vitae facilisis. Pellentesque a egestas quam. Nam quis lorem velit. Phasellus tincidunt faucibus sodales. Donec lacinia sem justo, ac feugiat magna interdum a. Nunc a elementum tortor. Donec condimentum, erat a vestibulum commodo, nunc ex mattis enim, a efficitur ex sem a nulla. Mauris sodales, quam et vestibulum congue, arcu risus consectetur leo, eu fringilla ipsum enim id magna. Aliquam gravida convallis orci. Vivamus eu tempus ipsum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc laoreet varius metus vitae bibendum. Nullam id nisl at magna efficitur vehicula. Phasellus mollis risus ut diam bibendum rutrum. Sed porttitor augue at pharetra viverra.</div>
        </a>
      </div>

    </div>
  </div>

</div><!-- End tabs -->



<!-- MODAL -->
<div class="modal fade" id="tc-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modal-label"></h4>
      </div>
      <div id="modal-body" class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- END MODAL -->
{% endblock %}

{% block css %}
  {{ block.super }}
  {% leaflet_css %}
  <style>
  .well {
    margin-bottom:10px;
  }
  </style>
{% endblock %}


{% block javascript %}
  {{ block.super }}

  {% javascript 'project' %}

  {% leaflet_js %}

  <script type="text/javascript">
  $( document ).ready(function() {
    'use strict';
    //
    // Map handler
    //
    function map_init_basic (map, options) {
        map.setView(new L.LatLng('{{ object.lat_long.latitude }}', '{{ object.lat_long.longitude }}'), 9);
        L.marker(['{{ object.lat_long.latitude }}', '{{ object.lat_long.longitude }}']).addTo(map);
    }

    //
    // Handle tabs
    //
    $('#project-tabs a').click(function (e) {
      e.preventDefault()
      $(this).tab('show')
    });

    //
    // Modal Window loaders and settings
    //
    $('#tc-modal').on('show.bs.modal', function (e) {
      // load appropriate content
      var source = $(e.relatedTarget);
      var data_source = $('#'+ source.data().source);
      $('#modal-label').html(source.data().title);
      $('#modal-body').html(data_source.html());
    });

    //
    // F.A.Q collapsable setting
    //
    $('.faq').on('click', function (e) {
      e.preventDefault();
      $($(this).find('.answer')).collapse('toggle');
    })

    //
    // RSS and News loader
    //
    window.embedLoadingAnimation($("#project-news"));

    $("#project-news").rss("https://today-capital.de/feed/", {
      limit: 6,
      dateFormat: 'MMMM Do, YYYY',
      dateLocale: 'de',
      dateFormatFunction: function (datePublished) {
        return moment(datePublished).format('MMMM Do YYYY');
      },
      layoutTemplate: '<h3>{% trans "Latest News" %}</h3><div class="list-group">{entries}</div>',
      entryTemplate: '<a target="_NEW" href="{url}" class="list-group-item"><b>{title}</b><br/><em>{date}</em><br/>{shortBodyPlain}</a>',
    }, function () {
      window.removeEmbedLoadingAnimation($("#project-news"));
    });
  });
  </script>
{% endblock %}

elbow/apps/project/templates/project/project-list.html
{% extends 'project/base.html' %}{% load i18n static project_tags %}

{% block page_title %}List of Projects{% endblock %}
{% block page_description %}A list of available projects{% endblock %}
{% block page_keywords %}list,projects{% endblock %}

{% block page_header %}
<div class="page-header clearfix">
    <div class="col-md-12" style="padding:0px;">
      <h1>{% trans 'Current Projects' %}<br/><small>{% blocktrans %}A list of our current projects{% endblocktrans %}</small></h1>
    </div>
</div>
<div class="clearfix"></div>
{% endblock %}


{% block content %}
{% project_preview project_list %}
{% endblock %}