elbow/apps/order/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.decorators.csrf import csrf_exempt

from .views import (OrderCreate,
                    OrderLoanAgreementView,
                    OrderPayment,
                    UserOrderList,
                    OrderDetail,
                    OrderWebhook)

urlpatterns = patterns('',
                       url(r'^$',
                           UserOrderList.as_view(),
                           name='user_list'),

                       url(r'^(?P<project_slug>[\w-]+)/order/$',
                           OrderCreate.as_view(),
                           name='create'),

                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>[\w-]+)/loan-agreement/$',
                           OrderLoanAgreementView.as_view(),
                           name='loan_agreement'),

                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>.*)/payment/$',
                           OrderPayment.as_view(),
                           name='payment'),

                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>[\w-]+)/$',
                           OrderDetail.as_view(),
                           name='detail'),

                       #
                       # Payment integration, All are webhooks
                       #
                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>[\w-]+)/payment/successful/$',
                           OrderDetail.as_view(template_name='order/order-payment_success.html'),
                           name='payment_success'),

                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>[\w-]+)/payment/failure/$',
                           OrderDetail.as_view(template_name='order/order-payment_failed.html'),
                           name='payment_failure'),

                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>[\w-]+)/payment/webhook/$',
                           csrf_exempt(OrderWebhook.as_view()),
                           name='payment_webhook'),)

elbow/apps/project/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.generic import TemplateView, ListView

from .models import Project
from .views import ProjectDetailView, PDFPermalinkView


urlpatterns = patterns('',
                       url(r'^project-api/$', TemplateView.as_view(template_name='project/api-project-list.html')),
                       url(r'^$',
                           ListView.as_view(template_name='project/project-list.html',
                                            model=Project,
                                            queryset=Project.objects.public()),
                           name='list'),

                       url(r'^(?P<slug>[\w-]+)/media/(?P<media_slug>[\w-]+)/permalink/$',
                           PDFPermalinkView.as_view(),
                           name='media_permalink'),

                       url(r'^(?P<slug>[\w-]+)/$',
                           ProjectDetailView.as_view(),
                           name='detail'),)

elbow/urls.py
# -*- coding: UTF-8 -*-
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.decorators.cache import never_cache

from elbow.apps.public.views import LoginView, SignupView

admin.site.site_header = 'Todayhaus Administration'


urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^api/v1/', include('elbow.apps.api.urls', namespace='api')),

    # Projects
    url(r'^projects/', include('elbow.apps.project.urls', namespace='project')),
    # Orders
    url(r'^orders/', include('elbow.apps.order.urls', namespace='order')),
    # Documents
    url(r'^documents/', include('elbow.apps.document.urls', namespace='document')),
    # Paymill
    # url(r'^paymill/', include('dj_paymill.urls', namespace='paymill')),
    # User Auth
    # url(r'^auth/token/', 'rest_framework_jwt.views.obtain_jwt_token'),
    # url(r'^auth/token/refresh/', 'rest_framework_jwt.views.refresh_jwt_token'),
    # url(r'^auth/', include('rest_auth.urls')),
    # url(r'^auth/registration/', include('rest_auth.registration.urls')),
    url(r'^accounts/login/', never_cache(LoginView.as_view()), name='account_login'),
    url(r'^accounts/signup/', never_cache(SignupView.as_view()), name='account_signup'),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^', include('elbow.apps.public.urls', namespace='public')),
    url(r'^p/', include('pages.urls')), # check public/urls.py
    url(r'^robots\.txt', include('robots.urls')),
    url(r'^', include('django.contrib.auth.urls')),

) + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elbow/apps/order/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils import formats
from django.conf import settings
from django.core import validators

from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _
from django_countries.widgets import CountrySelectWidget

from pinax.eventlog.models import log

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Field, Submit, HTML, Button
from crispy_forms.bootstrap import PrependedAppendedText

from decimal import Decimal
from moneyed import Money, EUR


from elbow.apps.order.models import Order
from elbow.apps.order.services import LoanAgreementCreatePDFService

from elbow.apps.public.services import SendEmailService
from .apps import ORDER_PAYMENT_TYPE

import datetime
from dateutil.relativedelta import relativedelta

DEFAULT_CURRENCY_SYMBOL = getattr(settings, 'DEFAULT_CURRENCY_SYMBOL', '€')
DATE_18_YEARS_AGO = datetime.datetime.today() - relativedelta(years=18)
DEFAULT_DATE = datetime.datetime.today() - relativedelta(years=25)

YEARS = [year for year in xrange(1900, DATE_18_YEARS_AGO.year + 1)]


class CreateOrderForm(forms.Form):
    amount = forms.DecimalField(label=_('Amount to invest'),
                                max_digits=8,
                                decimal_places=0,
                                min_value=500,
                                required=True)

    title = forms.ChoiceField(label=_('Title'), choices=(('Mr', _('Mr')), ('Mrs', _('Mrs')),))

    customer_first_name = forms.CharField(label=_('First name'),
                                          required=True)

    customer_last_name = forms.CharField(label=_('Last name'),
                                         required=True)

    company_name = forms.CharField(label=_('Name of Company'),
                                   help_text=_('If applicable'),
                                   required=False)

    dob = forms.DateField(label=_('Date of Birth'),
                          initial=DEFAULT_DATE.date,
                          widget=forms.SelectDateWidget(years=YEARS))

    address_1 = forms.CharField(label=_('Address'),
                                help_text=_('Line 1 of address'),
                                required=True)

    address_2 = forms.CharField(label='',
                                help_text=_('Line 2 of address'),
                                required=False)

    postcode = forms.CharField(label=_('Post code'),
                               required=True)

    city = forms.CharField(label=_('City'),
                           required=True)

    country = forms.CharField(label=_('Country'),
                              initial=_('Germany'),
                              required=True)

    payment_type = forms.ChoiceField(label=_('How to pay'),
                                     initial=ORDER_PAYMENT_TYPE.debit,
                                     choices=ORDER_PAYMENT_TYPE.get_choices(),
                                     help_text=_('Please select a payment type'),
                                     widget=forms.RadioSelect)

    disclosure = forms.BooleanField(label=_(u'You want to invest 1000,00 &euro; or more and therefore, must agree to the loan contract in order to proceed'),
                                    widget=forms.CheckboxInput,
                                    required=False)

    t_and_c = forms.BooleanField(label=_('I agree to the site <a target=\"_NEW\" href="{url}">Terms & Conditions</a>'),
                                 widget=forms.CheckboxInput)

    has_read_investment_contract = forms.BooleanField(label=_('I have read and agree to be bound to the terms of the <a target=\"_NEW\" href="{url}">investment contract</a>.'),
                                                      widget=forms.CheckboxInput)

    has_read_loan_agreement_contract = forms.BooleanField(label=_('I have read and agree to the terms of the <a target=\"_NEW\" href="{url}">loan agreement</a>.'),
                                                          widget=forms.CheckboxInput)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.project = kwargs.pop('project', None)

        self.available_from_message = None
        if self.project.date_available:
            available_from = formats.date_format(self.project.date_available, "SHORT_DATE_FORMAT")
            self.available_from_message = _(u'Available from %(available_from)s') % {'available_from': available_from}

        if self.user is None:
            raise Exception('user must be passed into the Form')
        if self.project is None:
            raise Exception('project must be passed into the Form')

        super(CreateOrderForm, self).__init__(**kwargs)
        self.fields['customer_first_name'].initial = self.user.first_name
        self.fields['customer_last_name'].initial = self.user.last_name

        #
        # Set minimum amount to that of the project
        # and the widget min value too
        #
        min_amount = int(self.project.minimum_investment.amount)
        self.fields['amount'].min_value = min_amount
        self.fields['amount'].widget.attrs['min'] = min_amount
        del self.fields['amount'].validators[0]
        self.fields['amount'].validators.append(validators.MinValueValidator(min_amount))

        #
        # Setup minimum and max investment if the project has it
        # Order is important
        #
        if self.project.minimum_investment:
            self.fields['amount'].min_value = self.project.minimum_investment.amount

        if self.project.maximum_investment:
            self.fields['amount'].max_value = self.project.maximum_investment.amount

        #
        # Setup help text in the case of min and max investment
        # Order is important
        #
        if self.project.minimum_investment:
            self.fields['amount'].help_text = _(u'A minimum of {minimum} is required').format(minimum=unicode(self.project.minimum_investment))

        if self.project.maximum_investment:
            self.fields['amount'].help_text = _(u'A minimum of {minimum} and a maximum of {maximum}, is required').format(minimum=unicode(self.project.minimum_investment),
                                                                                                                          maximum=unicode(self.project.maximum_investment))
        # Setup the loan_agreement and term_sheet        
        self.fields['t_and_c'].label = self.fields['t_and_c'].label.format(url=settings.TERMS_AND_CONDITIONS_URL)

        if self.project.term_sheet_doc:
            self.fields['has_read_investment_contract'].label = self.fields['has_read_investment_contract'].label.format(url=self.project.term_sheet_doc.url)

        if self.project.loan_agreement_doc:
            self.fields['has_read_loan_agreement_contract'].label = self.fields['has_read_loan_agreement_contract'].label.format(url=self.project.loan_agreement_doc.url)

    @property
    def helper(self):
        helper = FormHelper(self)

        helper.form_action = ''
        helper.form_show_errors = True
        helper.render_unmentioned_fields = True

        show_has_agreed_to_loan_agreement_terms = 'hide'
        if self.is_large_sum() is True:
            show_has_agreed_to_loan_agreement_terms = ''

        if self.project.is_available_for_investment is True:
            form_submit_button = Submit('submit', _(u'Invest Now'), css_class='btn btn-primary btn-lg')
        else:
            form_submit_button = Button('button', self.available_from_message, css_class='btn btn-default btn-lg not-yet-available')

        helper.layout = Layout(
                               Fieldset(_('Investment Amount'),
                                        PrependedAppendedText('amount', DEFAULT_CURRENCY_SYMBOL, '.00'),
                                        HTML('<div class="input-group"><label for="" class="control-label">%s:</label>&nbsp;<span id="interest_rate_pa"></span></div>' % (_('Interest Rate p.a'),)),
                                        HTML('<div class="input-group"><label for="" class="control-label">%s:</label>&nbsp;<span id="interest_term"></span></div>' % (_('Interest Term'),)),
                                        HTML('<span id="accrue-target" class=""></span>'),
                                        HTML(u'<div id="loan-contract" class="{show_has_agreed_to_loan_agreement_terms} alert alert-warning clearfix">'.format(show_has_agreed_to_loan_agreement_terms=show_has_agreed_to_loan_agreement_terms)),
                                        Field('disclosure'),
                                        HTML('</div>'),
                               ),
                               Fieldset(_('Investor Details'),
                                        'title',
                                        'customer_first_name',
                                        'customer_last_name',
                                        'dob',
                               ),
                               Fieldset(_('Company Details'),
                                        'company_name',
                               ),
                               Fieldset(_('Postal Address'),
                                        'address_1',
                                        'address_2',
                                        'postcode',
                                        'city',
                                        'country',
                               ),
                               Fieldset(_('Payment'),
                                        'payment_type',
                                        't_and_c',
                                        'has_read_investment_contract' if self.fields.get('has_read_investment_contract') else None,

elbow/apps/order/templates/order/_address.html
{{ address_1 }}<br/>
{%if address_2 %}{{ address_2 }}<br/>{% endif %}
{{ postcode }} {{ city }}<br/>
{{ country }}

elbow/apps/order/templates/order/_user_orders_for_project.html
{% load i18n humanize djmoney %}
{% if user.is_authenticated %}
<h3>{% trans 'Previous Orders' %}</h3>
<ul class="list-unstyled">
  {% for order in order_list %}
  <li>
    <a href="{% url 'order:detail' order.project.slug order.uuid %}">{% money_localize order.amount %} {{ order.created_at|naturaltime }} for {{ order.customer_name }}</a>
  </li>
  {% empty %}
  {% endfor %}
</ul>
{% endif %}

elbow/apps/order/templates/order/base.html
{% extends 'base.html' %}

elbow/apps/order/templates/order/order-create.html
{% extends 'order/base.html' %}{% load i18n static crispy_forms_tags djmoney embed_video_tags project_tags %}
{% load crispy_forms_filters %}

{% block page_title %}{% blocktrans with project=project.name %}{{ project }} - Invest Now{% endblocktrans %}{% endblock %}
{% block page_description %}{% blocktrans with project=project.name %}Invest in {{ project }}{% endblocktrans %}{% endblock %}
{% block page_keywords %}invest,project,and-development,development{% endblock %}

{% block page_header %}
<div class="page-header clearfix">
    <div class="col-md-12" style="padding:0px;">
      <h1>{% blocktrans with project=project.name %}Invest in {{ project }}{% endblocktrans %}<br/><small>{{ project.proposition }}</small></h1>
    </div>
</div>
<div class="clearfix"></div>
{% endblock %}


{% block content %}
<div class="row">

  <div class="col-sm-5">

    <div class="col-sm-12" style="padding:0px;">
          {% project_stats project %}
    </div>

    <div class="col-sm-12" style="padding:0px;">
      {% project_docs project %}
      </ul>
    </div>

  </div>

  <div class="col-sm-7">
    <!-- <p>{{ project.description }}</p> -->
    {% crispy form %}
  </div>

</div>
{% endblock %}

{% block css %}
  {{ block.super }}
  <style>
  /* Remove the number input spinners */
  input[type='number'] {
      -moz-appearance:textfield;
  }
  input::-webkit-inner-spin-button, 
  input::-webkit-outer-spin-button { 
    -webkit-appearance: none; 
    margin: 0; 
  }

  fieldset {
    margin-top:30px;
  }
  #accrue-target div.form {
    display:none;
  }
  .selectdatewidget {
    width:25%;
    display:inline-flex;
  }
  .buttonHolder {
    text-align:center;
  }
  </style>
{% endblock %}

{% block javascript %}
  {{ block.super }}

  <script type="text/javascript">
  $( document ).ready(function() {
      'use strict';

      //
      // Interest calculator
      //
      var interest_rate_pa = '{{ project.interest_rate }}'.replace(',', '.');
      $('#interest_rate_pa').html(interest_rate_pa+' %');
      var display_interest_term = '{{ project.interest_term }}'.replace('m', ' {% trans "Months" %}')
      display_interest_term = display_interest_term.replace('y', ' {% trans "Years" %}')
      $('#interest_term').html(display_interest_term);

      $( '#accrue-target' ).accrue({
        mode: "basic",
        operation: "keyup",
        default_values: {
          amount: "0",
          rate: "{{ project.interest_rate }}%".replace(',', '.'),
          rate_compare: "1.49%",
          term: "{{ project.interest_term }}",
        },
        response_basic:
          //'<p><strong>Total Interest:</strong>&nbsp;€%total_interest%</p>',
          '',
        response_compare: "Save $%savings% in interest!",
        error_text: null,
        target_fields: {
          amount: $('#id_amount')
        }
      });

      //
      // Amount checker
      //
      $('#id_amount').on('keypress', function (e) {
        var kCode = (e.which || e.keyCode)
        // prevent any non number from being accepted
        if (kCode < 48 || kCode > 57) {
          e.preventDefault();
        }
      });

      $('#id_amount').on('change keyup', function (event) {
        var amount = parseInt($(this).val());

        if (amount > 1000) {
          // if the user wants more than 1k invested he needs a darllensvertrag
          $('#loan-contract').removeClass('hide').fadeIn();
        } else {
          $('#loan-contract').addClass('hide');
        }
      });
  });
  </script>
{% endblock %}
interest_rate_pa
interest_rate_total

elbow/apps/order/templates/order/order-detail.html
{% extends 'order/base.html' %}{% load i18n static crispy_forms_tags djmoney embed_video_tags %}

{% block page_title %}{% endblock %}
{% block page_description %}{% endblock %}
{% block page_keywords %}{% endblock %}

{% block page_header %}
<div class="page-header clearfix">
  <h1>Order Detail</h1>
</div>
{% endblock %}

{% block content %}
<div class="row">

  <div class="col-md-12">
    <p class="lead"></p>
  </div>

  <div class="col-offset-1 col-sm-6">
  </div>

</div>
{% endblock %}

elbow/apps/order/templates/order/order-large_sum_agreement.html
{% extends 'order/base.html' %}{% load i18n static crispy_forms_tags djmoney embed_video_tags %}
{% load crispy_forms_filters %}

{% block page_title %}{{ project.name }} - Large Sum Agreement{% endblock %}
{% block page_description %}Invest in {{ project.name }}{% endblock %}
{% block page_keywords %}invest,project,and-development,development{% endblock %}

{% block page_header %}
<div class="page-header clearfix">
  <h1>Large Investment amount Agreement for {{ project.name }}</h1>
  <p>{{ project.proposition }}</p>
  <div class="col-md-4">
  &nbsp;
  </div>
  <div class="col-md-8 text-right">
  &nbsp;
  </div>
</div>
{% endblock %}

{% block content %}

<div class="row">

  <div class="col-md-12">
    <p class="lead">{{ project.description }}</p>
  </div>

  <div class="col-offset-1 col-sm-6">
    {% crispy form %}
  </div>

</div>
{% endblock %}

elbow/apps/order/templates/order/order-list.html
{% extends 'order/base.html' %}{% load i18n static humanize djmoney %}
{% load crispy_forms_filters %}

{% block page_title %}Your Investments{% endblock %}
{% block page_description %}Invest in {{ project.name }}{% endblock %}
{% block page_keywords %}invest,project,and-development,development{% endblock %}

{% block page_header %}
<div class="page-header clearfix">
  <h1>{% trans 'Investment History' %}</h1>
</div>
{% endblock %}

{% block content %}

<div class="row" id="order-list">

  <div class="col-sm-12">
  {% for order in object_list %}
    <div class="row clearfix">
      <div class="col-xs-3">
        <h4 class="header"><a href="{{ order.project.url }}">{{ order.project }}</a></h4>
        <a href="{{ order.project.url }}"><img class="img img-responsive" src="{% get_media_prefix %}{{ order.project.image }}" alt="" title=""/></a>
      </div>
      <div class="col-xs-2">
        <b>{% money_localize order.amount %}</b>
        <br/><em>{{ order.payment_type }}</em>
        <br/><b>{{ order.created_at|naturaltime }}</b><br/><small>{{ order.created_at }}</small>
      </div>
      <div class="col-xs-3">
        <p><b>{{ order.customer_name }}</b></p>
        <p>
        {{ order.address }}<br/>
        {{ order.country }}
        {{ order.transaction_id }}
        {{ order.tracking_number }}
        </p>
      </div>
      <div class="col-xs-2">{{ order.status }}</div>
      <div class="col-xs-2">
        {% if order.can_continue_process %}<a href="{{ order.url }}" class="btn btn-sm btn-info">{% trans 'Continue' %}</a>{% endif %}
        {% if order.can_continue_process or order.status == 'pending' %}<a href="javascript:;" data-url="{{ order.url }}" class="order-lifecycle-event btn btn-sm btn-warning">{% trans 'Cancel'  %}</a>{% endif %}
        <!-- {% if order.status == 'cancelled' %}<a href="javascript:;" data-url="{{ order.url }}" class="order-lifecycle-event btn btn-sm btn-danger">{% trans 'Delete'  %}</a>{% endif %} -->
      </div>
    </div>
  {% empty %}
    <div class="row clearfix">
      <div class="col-xs-12">
        <p><b>{% trans 'No investments found' %}</b></p>
        <p><a href="{% url 'project:list' %}" class="btn btn-primary">{% trans 'Invest now' %}</a></p>
      </div>
    </div>
  {% endfor %}
  </div>

</div>
{% endblock %}


{% block css %}
<style>
.row:nth-child(1) {
    margin-top:0px;
}
.row {
  margin-top:25px;
  padding-bottom:25px;
  border-bottom:solid #eee 1px;
}
#order-list h4.header {
  margin-top:0px;
}
</style>
{% endblock %}


{% block javascript %}
<script>
'use strict';
$( document ).ready(function( $ ) {

      $('.order-lifecycle-event').on('click', function (event) {
        event.preventDefault();
        var button = $(this);
        var url = button.data().url;
        console.log(url);
        $.ajax({
            url: url,
            type: 'POST',
            data: JSON.stringify({
            }),
            dataType: 'json',
            contentType: "application/json",
            beforeSend: function (request) {
                request.setRequestHeader("X-CSRFToken", '{{csrf_token}}');
                // disable the button
                button.prop('disabled', true);
            },
            error: function ( data ) {
                var payload = data.responseJSON;
                // enable the button again
                button.prop('disabled', false);
            },
            success: function ( data ) {
                //console.log(data)
                if ( data.status == 200 ) {
                }
                button.prop('disabled', false);
                document.location.reload();
            }
        });

      });

});
</script>
{% endblock %}

elbow/apps/order/templates/order/order-loan_agreement.html
{% extends 'order/base.html' %}{% load i18n crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block page_title %}{{ project.name }} - Loan Agreement{% endblock %}
{% block page_description %}Invest in {{ project.name }}{% endblock %}
{% block page_keywords %}invest,project,and-development,development{% endblock %}

{% block page_header %}
<div class="page-header clearfix">
  <h1>{% trans 'Your Loan Agreement' %}</h1>
  <p>{% blocktrans with project_name=project.name %}Thank you for deciding to support the {{ project_name }} project with your investment.' {% endblocktrans %}</p>
  <div class="col-md-4">
  &nbsp;
  </div>
  <div class="col-md-8 text-right">
  &nbsp;
  </div>
</div>
{% endblock %}

{% block content %}
<div class="row">

  <div class="col-md-12">
    <p>{% blocktrans %}You can download the generated Loan Agreement by clicking on the button below.{% endblocktrans %}</p>
  </div>

  <div class="col-md-12" style="margin:10px 0px;">
    <a href="{{ document.url }}" target="_NEW" class="btn btn-lg btn-info">{% trans 'Download Loan Agreement' %}</a>
  </div>

  <div class="col-offset-1 col-sm-6">
    {% crispy form %}
  </div>

</div>
{% endblock %}

elbow/apps/order/templates/order/order-payment.html
{% extends 'order/base.html' %}{% load i18n static crispy_forms_tags djmoney embed_video_tags %}
{% load crispy_forms_filters %}

{% block page_title %}{{ project.name }} - Payment{% endblock %}
{% block page_description %}Invest in {{ project.name }}{% endblock %}
{% block page_keywords %}invest,project,and-development,development{% endblock %}

{% block page_header %}
<div class="page-header clearfix">
  <h1>{% trans 'Payment Details' %} - {{ project.name }}</h1>
  <p>{{ project.proposition }}</p>
</div>
{% endblock %}

{% block content %}

<div class="row">

  {% if SECUPAY_DEMO %}
  <div class="col-md-12">
    <div class="alert alert-danger">
      <p><b>Secupay DEMO MODE</b>: No actual payment will take place.</p>
      <p>Please use the following IBAN numbers for testing<br/><a href="http://www.iban-bic.com/sample_accounts.html" target="_NEW">source</a></p>

      <p><b>CORRECT:</b><br/>
      <b>Nationale Kontonummer:</b> 0648489890<br/>
      <b>BLZ:</b> 50010517<br/>
      <b>IBAN:</b> DE12500105170648489890</p>
      <p>&nbsp;</p>
      <p><b>INCORRECT:</b><br/>
      <b>Nationale Kontonummer:</b> 064847930<br/>
      <b>BLZ:</b> 50010517<br/>
      <b>IBAN:</b> DE1206484793050010517</p>
    </div>
  </div>
  {% endif %}

  {% if order.payment_type == 'prepay' %}

    <!--<div class="col-md-12 text-center" style="padding-bottom:20px;">
      <a href="{{ project.url }}" class="btn btn-lg btn-info">{% trans 'Back to Project' %}</a>
    </div>-->
    <div class="col-md-12 text-center" style="padding-bottom:20px;">
      <em>Sie können das Fenster jetzt schließen</em>
    </div>

    <div class="col-md-12">
      <h2>{% trans 'Please make payment out to' %}</h2>
      <div class="col-xs-12 well well-lg">
        <b>{% trans 'Bank Name' %}:</b> {{ SECUPAY_BANK_DATA.bankname }}<br/>
        <!--<b>{% trans 'Bankcode' %}:</b> {{ SECUPAY_BANK_DATA.bankcode }}<br/>-->
        <b>{% trans 'Account Owner' %}:</b> {{ SECUPAY_BANK_DATA.accountowner }}<br/>
        <b>{% trans 'IBAN' %}:</b> {{ SECUPAY_BANK_DATA.iban }}<br/>
        <b>{% trans 'BIC' %}:</b> {{ SECUPAY_BANK_DATA.bic }}<br/>
        <!--<b>{% trans 'Account No.' %}:</b> {{ SECUPAY_BANK_DATA.accountnumber }}<br/>-->
        <hr/>
        <p class="lead"><b><em>{% trans 'Customer Reference' %}:</em></b> {{ order.tracking_number }}</p>
      </div>
    </div>

  {% else %}

    <div class="col-md-12">
      <iframe id="secupay" src="{{ order.data.iframe_url }}" width="100%" height="640"></iframe>
    </div>

  {% endif %}

</div>
{% endblock %}


{% block css %}
<style>
iframe#secupay {
  width:100%;
  min-height:640px;
  max-height:640px;
  border:solid #ccc 0px;
}
</style>
{% endblock %}

elbow/apps/order/templates/order/order-payment_failed.html
{% extends 'order/base.html' %}{% load i18n static crispy_forms_tags djmoney embed_video_tags %}
{% load crispy_forms_filters %}

{% block page_title %}{% blocktrans with name=order.project.name %} {{ name }} - Payment Failed{% endblocktrans %}{% endblock %}
{% block page_description %}{% blocktrans with name=order.project.name %}Payment failed for your investment {{ name }}{% endblocktrans %}{% endblock %}


{% block page_header %}
<div class="page-header clearfix">
  <h1>{% blocktrans with name=order.project.name %}Payment failed for {{ name }}{% endblocktrans %}</h1>
</div>
{% endblock %}

{% block content %}

<div class="row">

  <div class="well well-lg">
    <p>{% trans 'Could not process payment, please try again.' %}</p>
    <p><a href="{% url 'order:create' project_slug=order.project.slug %}">{% trans 'Click here' %}</a></p>
  </div>

  <!--<p>
    <a href="{{ project.url }}" class="btn btn-lg btn-info">{% trans 'Back to Project' %}</a>
  </p>-->
    <div class="col-md-12 text-center" style="padding-bottom:20px;">
      <em>Sie können das Fenster jetzt schließen</em>
    </div>


</div>
{% endblock %}