elbow/apps/order/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.views.decorators.csrf import csrf_exempt

from .views import (OrderCreate,
                    OrderLoanAgreementView,
                    OrderPayment,
                    UserOrderList,
                    OrderDetail,
                    OrderWebhook)

urlpatterns = patterns('',
                       url(r'^$',
                           UserOrderList.as_view(),
                           name='user_list'),

                       url(r'^(?P<project_slug>[\w-]+)/order/$',
                           OrderCreate.as_view(),
                           name='create'),

                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>[\w-]+)/loan-agreement/$',
                           OrderLoanAgreementView.as_view(),
                           name='loan_agreement'),

                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>.*)/payment/$',
                           OrderPayment.as_view(),
                           name='payment'),

                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>[\w-]+)/$',
                           OrderDetail.as_view(),
                           name='detail'),

                       #
                       # Payment integration, All are webhooks
                       #
                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>[\w-]+)/payment/successful/$',
                           OrderDetail.as_view(template_name='order/order-payment_success.html'),
                           name='payment_success'),

                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>[\w-]+)/payment/failure/$',
                           OrderDetail.as_view(template_name='order/order-payment_failed.html'),
                           name='payment_failure'),

                       url(r'^(?P<project_slug>[\w-]+)/order/(?P<uuid>[\w-]+)/payment/webhook/$',
                           csrf_exempt(OrderWebhook.as_view()),
                           name='payment_webhook'),)

elbow/urls.py
# -*- coding: UTF-8 -*-
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.decorators.cache import never_cache

from elbow.apps.public.views import LoginView, SignupView

admin.site.site_header = 'Todayhaus Administration'


urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^api/v1/', include('elbow.apps.api.urls', namespace='api')),

    # Projects
    url(r'^projects/', include('elbow.apps.project.urls', namespace='project')),
    # Orders
    url(r'^orders/', include('elbow.apps.order.urls', namespace='order')),
    # Documents
    url(r'^documents/', include('elbow.apps.document.urls', namespace='document')),
    # Paymill
    # url(r'^paymill/', include('dj_paymill.urls', namespace='paymill')),
    # User Auth
    # url(r'^auth/token/', 'rest_framework_jwt.views.obtain_jwt_token'),
    # url(r'^auth/token/refresh/', 'rest_framework_jwt.views.refresh_jwt_token'),
    # url(r'^auth/', include('rest_auth.urls')),
    # url(r'^auth/registration/', include('rest_auth.registration.urls')),
    url(r'^accounts/login/', never_cache(LoginView.as_view()), name='account_login'),
    url(r'^accounts/signup/', never_cache(SignupView.as_view()), name='account_signup'),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^', include('elbow.apps.public.urls', namespace='public')),
    url(r'^p/', include('pages.urls')), # check public/urls.py
    url(r'^robots\.txt', include('robots.urls')),
    url(r'^', include('django.contrib.auth.urls')),

) + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>{% load pipeline i18n pages_tags static flags %}{% load_pages %}
{% get_pages_with_tag "main" as pages_main %}
{% get_pages_with_tag "footer" as pages_footer %}
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}{% get_available_languages as LANGUAGES %}
{% get_language_info for LANGUAGE_CODE as current_lang %}
<html lang="{{ LANGUAGE_CODE|default:"de" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
  <head>
    <meta charset="utf-8">
    <title>{% block page_title %}TodayCapital.de{% endblock %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="{% block page_description %}{% endblock %}">
    <meta name="keywords" content="{% block page_keywords %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="{{ GOOGLE_SITE_VERIFICATION }}" />

    {% block page_itemprops %}{% endblock %}

    <!-- SocialSharing -->
    {% block page_ogprops %}{% endblock %}

    {% stylesheet 'base' %}
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    {% block css %}{% endblock %}

  </head>
  <body>

    {% include 'navigation.html' %}

    {% block outer_content %}{% endblock %}

    <div id="outer-wrapper" class="container">
        {% block page_header %}{% endblock %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
        {% block content %}{% endblock %}
    </div><!-- end id="outer-wrapper" -->

    <!-- FOOTER -->
    {% include 'footer.html' %}

    <script type="text/javascript">
      window.STATIC_URL = '{% get_static_prefix %}';
      window.MEDIA_URL = '{% get_media_prefix %}';

      /**
      * Embed our loading animation into the targets html
      */
      window.embedLoadingAnimation = function (target) {
        var animated_svg = '<object class="loading" data="'+ window.STATIC_URL +'img/ring-alt.svg" width="45" height="45" style="margin: 0 auto;width:100%;" type="image/svg+xml"> <img src="'+ window.STATIC_URL +'img/ring-alt.gif" width="45" height="45" alt="{% trans 'Please wait' %}" /></object>';
        target.html(animated_svg);
      }
      /**
      * Remove the targets loading animation
      * used from promise and callbacks
      */
      window.removeEmbedLoadingAnimation = function (target) {
        target.find('.loading').remove();
      }
    </script>
    {% javascript 'base' %}
    {% block javascript %}{% endblock %}
    <script>
      /**
      * Prevent users from double clicking on submit
      *
      */
      $( document ).ready(function() {
        jQuery.fn.preventDoubleSubmission = function() {

            var last_clicked, time_since_clicked;

            $(this).bind('submit', function(event){

            if(last_clicked) {
              time_since_clicked = event.timeStamp - last_clicked;
            }

            last_clicked = event.timeStamp;

            if(time_since_clicked && time_since_clicked < 2000) {
              //console.log('no submit')
              return false;
            } else {
              //console.log('submit')
              return true;
            }
          });
        };

        $('form').preventDoubleSubmission();

      });
    </script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-63335981-10', 'auto');
      ga('set', 'anonymizeIp', true);
      ga('send', 'pageview');
    </script>
  </body>
</html>

templates/footer.html
{% load i18n pages_tags static flags %}{% load_pages %}
<footer class="container">
  <!-- <p class="pull-right"><a href="#">{% trans 'Back to top' %}</a></p> -->
  <p>&copy; 2016 TodayCapital GmbH</p>
  <ul class="nav navbar-nav">
<!--   {% for page in pages_footer %}
      {% pages_menu page %}
  {% endfor %} -->
  </ul>
</footer>

templates/navigation.html
{% load i18n pages_tags static flags %}{% load_pages %}
<nav class="navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img class="img img-responsive" style="height:42px;" src="{% get_static_prefix %}img/todaycapital-logo-white-bg-160.png" alt="" title="" /></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {% if not user.is_authenticated %}
        <li><a href="{% url 'account_login' %}">{% trans 'Login' %}</a></li>
        <li><a href="{% url 'account_signup' %}">{% trans 'Register' %}</a></li>
        {% else %}

          <li role="separator" class="divider"></li>
          {# <li><a href="{% url 'account_email' %}">{% trans 'Email Settings' %}</a></li> #}
          {# <li><a href="{% url 'order:user_list' %}">{% trans 'Investment History' %}</a></li> #}
          <li><a href="{% url 'account_change_password' %}">{% trans 'Change Password' %}</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="{% url 'account_logout' %}">{% trans 'Logout' %}</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>